// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.1.0.0
//      SpecFlow Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace MenuCycleApiTests_ci.MenuCycleItems.Features
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.1.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("MenuCycleItemEntites")]
    public partial class MenuCycleItemEntitesFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "MenucycleItemEntities.feature"
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "MenuCycleItemEntites", null, ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void FeatureBackground()
        {
#line 4
  #line 5
    testRunner.Given("the executable Menuservice stored procedure \'sp_delete_menucycle_by_customer_id\' " +
                    "with id \'39\' is executed against Staging Database", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 6
    testRunner.Given("user can access the MenuService API with userID \'AutomationTestUser1\' and Org \'or" +
                    "ganisationName\' contentType \'application/vnd.siren+json\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 7
     testRunner.When("user issues \'POST\' request against the \'/MenuCycles\' and \'\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 8
     testRunner.And("the \'single\' group \'95\' and \'96\' request sent to server", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 9
     testRunner.Then("No errors are returned by server", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 10
      testRunner.And("user should get the last menuCycleId from response", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 11
    testRunner.Given("user can access the MenuService API with userID \'AutomationTestUser1\' and Org \'or" +
                    "ganisationName\' contentType \'application/vnd.siren+json\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 12
     testRunner.When("user issues \'POST\' request against a menucycle \'/MenuCycles/\' and \'/items\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 13
      testRunner.And("Items request contains mealpriod 39 and the \'Menu\' with id 94", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 14
     testRunner.Then("No errors are returned by server", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("GET-MenuCycleItem  Entities links and Actions")]
        [NUnit.Framework.CategoryAttribute("MenuCycle_Entities")]
        public virtual void GET_MenuCycleItemEntitiesLinksAndActions()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("GET-MenuCycleItem  Entities links and Actions", new string[] {
                        "MenuCycle_Entities"});
#line 17
  this.ScenarioSetup(scenarioInfo);
#line 4
  this.FeatureBackground();
#line 18
    testRunner.Given("user can access the MenuService API with userID \'AutomationTestUser1\' and Org \'or" +
                    "ganisationName\' contentType \'application/vnd.siren+json\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 19
     testRunner.When("user issues \'GET\' request against a menucycle \'/MenuCycles/\' and \'/items\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 20
      testRunner.And("the request is sent to the server", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 21
     testRunner.Then("No errors are returned by server", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "class",
                        "rel"});
            table1.AddRow(new string[] {
                        "MenuCycleItem",
                        "/rels/menucycle/item"});
#line 22
      testRunner.And("the following MenuCycleItem entities are returned", ((string)(null)), table1, "And ");
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "href"});
            table2.AddRow(new string[] {
                        "http://ci-menuservice.fourth.com//MenuCycles/{0}"});
            table2.AddRow(new string[] {
                        "http://ci-menuservice.fourth.com//MenuCycles/{0}/Items"});
            table2.AddRow(new string[] {
                        "http://ci-menuservice.fourth.com//MenuCycles/{0}/Items?$skip=0&$top=20"});
            table2.AddRow(new string[] {
                        "http://ci-menuservice.fourth.com//MenuCycles/{0}/Items?$skip=20&$top=20"});
            table2.AddRow(new string[] {
                        "http://ci-menuservice.fourth.com//MenuCycles/{0}/Items?$skip=20&$top=20"});
#line 26
   testRunner.And("the following \'href\' links returned", ((string)(null)), table2, "And ");
#line hidden
            TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                        "method",
                        "title",
                        "type"});
            table3.AddRow(new string[] {
                        "GET",
                        "",
                        "application/vnd.siren+json;"});
            table3.AddRow(new string[] {
                        "GET",
                        "Current Page",
                        "application/vnd.siren+json;"});
            table3.AddRow(new string[] {
                        "GET",
                        "Next Page",
                        "application/vnd.siren+json;"});
            table3.AddRow(new string[] {
                        "GET",
                        "Last Page",
                        "application/vnd.siren+json;"});
            table3.AddRow(new string[] {
                        "GET",
                        "Menu Cycle",
                        "application/vnd.siren+json;"});
#line 34
      testRunner.And("the follwing links properties are returned", ((string)(null)), table3, "And ");
#line hidden
            TechTalk.SpecFlow.Table table4 = new TechTalk.SpecFlow.Table(new string[] {
                        "href"});
            table4.AddRow(new string[] {
                        "http://ci-menuservice.fourth.com//MenuCycles/{0}/Items"});
            table4.AddRow(new string[] {
                        "http://ci-menuservice.fourth.com//MenuCycles/{0}/Items"});
#line 41
      testRunner.And("the following \'Action href\' links returned", ((string)(null)), table4, "And ");
#line hidden
            TechTalk.SpecFlow.Table table5 = new TechTalk.SpecFlow.Table(new string[] {
                        "method",
                        "title",
                        "type",
                        "name"});
            table5.AddRow(new string[] {
                        "POST",
                        "Creates menu cycle\'s items",
                        "application/vnd.siren+json;",
                        "CreateItems"});
            table5.AddRow(new string[] {
                        "PUT",
                        "Replaces menu cycle\'s items",
                        "application/vnd.siren+json;",
                        "UpdateItems"});
#line 46
   testRunner.And("the following Actions are returned", ((string)(null)), table5, "And ");
#line 50
    testRunner.Given("user can access the MenuService API with userID \'AutomationTestUser1\' and Org \'or" +
                    "ganisationName\' contentType \'application/vnd.siren+json\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 51
     testRunner.When("user issues \'PUT\' request against a menucycle \'/MenuCycles/\' and \'/items\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 52
      testRunner.And("user update single item  with day 8 order 3 menuid 94 mealperiod 40 and recipeid " +
                    "900", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 53
     testRunner.Then("No errors are returned by server", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 54
      testRunner.And("user should get all menucyleitem id from the response", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 56
     testRunner.When("user issues \'DELETE\' request against a menucycle \'/MenuCycles/\' and \'/items\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 57
      testRunner.And("user delete multiple menucycleitems 2", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 58
      testRunner.And("the request is sent to the server", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 59
     testRunner.Then("No errors are returned by server", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
