// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.1.0.0
//      SpecFlow Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace MenuCycleApiTests_ci.MenuCycleItems.Features.SellPrices
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.1.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("GetItemSellPrice")]
    public partial class GetItemSellPriceFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "GET-ItemSellPrice.feature"
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "GetItemSellPrice", null, ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void FeatureBackground()
        {
#line 3
#line 4
    testRunner.Given("user can access the MenuService API with userID \'pgreen\' and Org \'Fourth\' content" +
                    "Type \'application/vnd.siren+json\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 5
     testRunner.When("user issues \'PUT\' request against the \'/MenuCycles\' and \'/30/items/1230/SellPrice" +
                    "s\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 6
      testRunner.And("the request contains SellpriceModel 1 and tariffId 4 and value 10 and Vat 10 quan" +
                    "tity 23 price 20 minprice 20 maxprice 10", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 7
      testRunner.And("the request is sent to the server", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 8
     testRunner.Then("No errors are returned by server", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("GET_UpdatedItemSellPrices properties actions and links")]
        [NUnit.Framework.CategoryAttribute("ItemSellPrices")]
        public virtual void GET_UpdatedItemSellPricesPropertiesActionsAndLinks()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("GET_UpdatedItemSellPrices properties actions and links", new string[] {
                        "ItemSellPrices"});
#line 11
this.ScenarioSetup(scenarioInfo);
#line 3
this.FeatureBackground();
#line 12
    testRunner.Given("user can access the MenuService API with userID \'pgreen\' and Org \'Fourth\' content" +
                    "Type \'application/vnd.siren+json\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 13
     testRunner.When("user issues \'GET\' request against the \'/MenuCycles\' and \'/30/items/1230/SellPrice" +
                    "s\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 14
      testRunner.And("the request is sent to the server", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 15
     testRunner.Then("No errors are returned by server", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "menuCycleId",
                        "menuCycleItemId",
                        "sellPricesModel",
                        "tariffId",
                        "value",
                        "vat",
                        "quantity",
                        "price",
                        "minimumPrice",
                        "maximumPrice"});
            table1.AddRow(new string[] {
                        "30",
                        "1230",
                        "FixedPrice",
                        "4",
                        "10.00",
                        "10.00",
                        "23",
                        "20.00",
                        "20.00",
                        "10.00"});
#line 16
   testRunner.And("the following itemSellPrice propertie collection is returned", ((string)(null)), table1, "And ");
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "class",
                        "rel"});
            table2.AddRow(new string[] {
                        "SellPrice",
                        "/rels/SellPrice"});
#line 19
      testRunner.And("the following sellprices entities are returned", ((string)(null)), table2, "And ");
#line hidden
            TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                        "href",
                        "method",
                        "title",
                        "type"});
            table3.AddRow(new string[] {
                        "http://ci-menuservice.fourth.com/MenuCycles/30/Items/1230/SellPrices",
                        "GET",
                        "",
                        "application/vnd.siren+json;"});
#line 22
   testRunner.And("the follwing links are returned", ((string)(null)), table3, "And ");
#line hidden
            TechTalk.SpecFlow.Table table4 = new TechTalk.SpecFlow.Table(new string[] {
                        "href",
                        "method",
                        "title",
                        "type",
                        "name"});
            table4.AddRow(new string[] {
                        "http://ci-menuservice.fourth.com/MenuCycles/30/Items/1230/SellPrices",
                        "POST",
                        "Creates menu cycle item\'s prices",
                        "application/vnd.siren+json;",
                        "CreateSellPrices"});
            table4.AddRow(new string[] {
                        "http://ci-menuservice.fourth.com/MenuCycles/30/Items/1230/SellPrices",
                        "PUT",
                        "Replaces menu cycle item\'s prices",
                        "application/vnd.siren+json;",
                        "UpdateSellPrices"});
#line 28
  testRunner.And("the following Actions are returned", ((string)(null)), table4, "And ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
